# Generated by Django 5.1.3 on 2024-12-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(default='images/farmer.jpg', upload_to='producers/'),
        ),
    ]
