# Generated by Django 5.1.3 on 2024-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(default='/images/producers/farmer.jpg', upload_to='images/producers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_img',
            field=models.ImageField(default='/images/olive-oil.jpg', upload_to='images/products/'),
        ),
    ]
