# Generated by Django 5.1.3 on 2024-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_producer_image_alter_product_p_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(default='images/producers/farmer.jpg', upload_to='images/producers/'),
        ),
    ]
