# Generated by Django 5.1.3 on 2024-12-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_producer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(default='producers/farmer.jpg', upload_to='producers/'),
        ),
    ]
