# Generated by Django 5.1.3 on 2024-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_producer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.ImageField(default='producers/farmer2.jpeg', upload_to='producers/'),
        ),
    ]
